version: 2

conda:
   environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9" # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python, mamba instead of conda for better build performance
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx content/"

sphinx:
  builder: html
  fail_on_warning: true