# configuration defaults
# https://jupyterbook.org/en/stable/customize/config.html

#######################################################################################
# book settings
title: Learn Brightway
author: Brightway Contributors © 2024
logo: auxiliary/logo.png
only_build_toc_files: true

#######################################################################################
# book settings

execute:
  execute_notebooks: false
  allow_errors: false

#######################################################################################
# HTML-specific settings

html:
  favicon: auxiliary/favicon.png
  use_repository_button: true
  # https://jupyterbook.org/en/stable/advanced/html.html#adding-a-license-to-your-html-footer
  extra_footer: |
    <p>
    All content is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>
    </p>

sphinx:
  config:
    html_show_copyright: false

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true

#######################################################################################
# executable content settings
# https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
# https://jupyterbook.org/en/stable/interactive/thebe.html

#launch_buttons:
#  notebook_interface: "classic"
#  binderhub_url: "https://mybinder.org"
#  thebe: false

repository:
  url: https://github.com/brightway-lca/brightway-learn
  branch: main

#######################################################################################
# bibliography settings

bibtex_bibfiles:
  - content/bibliography/references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false