# configuration defaults
# https://jupyterbook.org/en/stable/customize/config.html

#######################################################################################
# book settings
title: Brightway Learn
author: Brightway Contributors
logo: auxiliary/logo.png
only_build_toc_files: true

#######################################################################################
# book settings

execute:
  execute_notebooks: force
  allow_errors: false

#######################################################################################
# HTML-specific settings

html:
  favicon: auxiliary/favicon.png
  use_repository_button: true
  announcement: "⚠️ Brightway Learn is in Public Beta ⚠️"

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true

#######################################################################################
# executable content settings
# https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
# https://jupyterbook.org/en/stable/interactive/thebe.html

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  thebe: false

repository:
  url: https://github.com/brightway-lca/brightway-learn
  branch: main

#######################################################################################
# bibliography settings

bibtex_bibfiles:
  - bibliography/references.bib
sphinx:
  config:
    bibtex_reference_style: author_year