# build book project
# https://jupyterbook.org/en/stable/start/build.html
# jb build .

# publish book project to gh-pages
# https://jupyterbook.org/en/stable/start/publish.html
# ghp-import -n -p -f _build/html

title: Brightway Documentation
author: Brightway Contributors
logo: aux/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# executable content
# https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
# https://jupyterbook.org/en/stable/interactive/thebe.html
launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"
  thebe: true

# references
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/brightway-lca/jupyter-book-brightway-documentation
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# announcement banner
html:
  announcement: "Work in progress!"