name: jbook
channels:
    - conda-forge
dependencies:
    # core functionality
    - python=3.11 # https://anaconda.org/conda-forge/python/files
    # jupyter
    - jupyterlab=4.0.3 # https://anaconda.org/conda-forge/jupyterlab/files
    - jupyter-book=0.15.1 # https://anaconda.org/conda-forge/jupyter-book/files